Review
mikhaylov123ty/go_final_project pull request #1
Opened 2024-05-19 18:50 UTC by mikhaylov123ty

2024-05-20 19:00 UTC, just-musha requested changes
Привет! Вижу что была проделана большая работа!
Отмечу грамотную организацию кода по го проджект layout и выполнение всех заданий со звездочкой.
К сожалению, у меня не запустились тесты. Оставила коммент с ошибкой

2024-05-20 19:00 UTC, just-musha commented on cmd/main.go
> +	server := web.Init(os.Getenv("TODO_PORT"))
Здесь хорошо будет задать дефолтные значения для порта и файла. Сейчас было не очевидно, что нужно обязательно задать эти переменые. Можно конечно в ридми написать, но первый способ предпочтительней - более предсказуемо)

А переменные - возможность их переопределить

2024-05-20 19:00 UTC, just-musha commented on README.md
> +Директория `cmd` содержит основной файл проекта
Супер структурное подробное описание :+1:

2024-05-20 19:00 UTC, just-musha commented on cmd/main.go
> +	err = server.Start("web")
Полезно вывести в лог - на каком порту запускается сервер

2024-05-20 19:00 UTC, just-musha commented on internal/db/db.go
> +	db, err := sql.Open("sqlite", file)
Что-то не так с инициализацией БД, можешь проверить на чистом репозитории?
У меня тесты не проходят, ошибка:
```
--- FAIL: TestAddTask (0.05s)
    addtask_4_test.go:140: 
        	Error Trace:	/home/mbulatova/projects/yandex-homeworks/sprint-final/go_final_project-mikhaylov123ty/tests/addtask_4_test.go:140
        	            				/home/mbulatova/projects/yandex-homeworks/sprint-final/go_final_project-mikhaylov123ty/tests/addtask_4_test.go:165
        	Error:      	Received unexpected error:
        	            	no such table: scheduler
        	Test:       	TestAddTask
    addtask_4_test.go:141: 
```

2024-05-20 19:00 UTC, just-musha commented on internal/db/db.go
> +	db, err := sql.Open("sqlite", file)
Задаю порт и файл БД через перменные окружения (7540, scheduler.db), запускаю сервер отдельно, и затем тесты

2024-05-20 19:45 UTC, mikhaylov123ty commented on internal/db/db.go
> +	db, err := sql.Open("sqlite", file)
Файл с БД проверяется и создается в процессе запуска сервера, таблица создается, если файла БД нет.
Можно попробовать удалить файл scheduler.db, а затем запустить сервер еще раз. Есть предположение, что что-то стриггерило создание файла, раньше запуска сервера (любое обращение к файлу БД, те же тесты).
Проверял на нескольких пк, а так же в образе докер, проблему смог воспроизвести только если файл без таблицы уже находится в рабочей директории.

2024-05-21 19:28 UTC, just-musha requested changes
Супер!
Последние правки.Ещё несколько моментов подсветила, основное - это проверка существования таблицы мб более оптимально сделать и константы перемеситть из models куда-то. Остальное не крит.

2024-05-21 19:28 UTC, just-musha commented on README.md
> +Если необходимо изменить порт или файл, необходимо добавить переменные окружения в конфигурации run/debug проекта:
:+1:

2024-05-21 19:28 UTC, just-musha commented on internal/models/models.go
> +	CheckTableExistence = `SELECT * FROM scheduler;`
Может быть накладно возвращать все из бд, а если там много данных, мы не знаем
Можно подумать как проверить чисто существование таблицы

2024-05-21 19:28 UTC, just-musha commented on internal/models/models.go
> +	CreateTableQuery = `CREATE TABLE scheduler (
Константы с запросами нужно положить проближе к месту где они используются ( internal/db )

2024-05-21 19:28 UTC, just-musha commented on internal/models/models.go
> +	CreateTableQuery = `CREATE TABLE scheduler (
А вообще если что - можно прям в коде запросы сделать, это будет ок, тк они не переиспользуются и это облегчит понимание кода если запрос прям в нем, сразу все видно (не крит)

2024-05-21 19:28 UTC, just-musha commented on tests/nextdate_3_test.go
> +		//Добавил несколько кейсов для проверки с високосными годами
:+1:

2024-05-21 19:28 UTC, just-musha commented on internal/api/mainHandler.go
> +	case r.URL.Query().Has("id") == true:
Здесь не нужно метод тоже проверить тоже, что это GET ?

2024-05-22 07:55 UTC, mikhaylov123ty commented
Проверку на наличие таблицы переписал, действительно, так логичнее проверять таблицу, а не выгружать из нее все.
Константы перенес в модули, где они используются. Для запросов БД их оставил, т.к. удобно все же один раз определить рабочий запрос и не трогать его.
Добавил дополнительную проверку методу GET в запросе к tasks

2024-05-22 08:54 UTC, just-musha approved these changes
Отлично! Хороший получится сервис, структурный, легкий в поддержке. Применены знания с курса, и было дополнительно много всего сделано.
Отдельное спасибо за комментарии по изменениям, это облегчало процесс ревью.

Принимаю работу!

2024-05-22 08:54 UTC, just-musha commented on internal/api/mainHandler.go
> +	case r.Method == "GET" && r.URL.Query().Has("id") == true:
Сейчас обратила внимание что проверка на id есть внутри самого метода, и в других хендлерах тоже. Можно тогда здесь её убрать, для единообразия?

2024-05-22 14:42 UTC, mikhaylov123ty commented on internal/api/mainHandler.go
> +	case r.Method == "GET" && r.URL.Query().Has("id") == true:
Доработаю, спасибо!

2025-03-31 10:18 UTC, merged